# Generated by Django 3.0.4 on 2024-03-28 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opencabs', '0002_auto_20211120_2304'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rate',
            old_name='oneway_driver_charge',
            new_name='oneway_time',
        ),
        migrations.RenameField(
            model_name='rate',
            old_name='roundtrip_driver_charge',
            new_name='roundtrip_time',
        ),
        migrations.RenameField(
            model_name='vehicleratecategory',
            old_name='tariff_after_hours',
            new_name='tariff_after_kms',
        ),
        migrations.RenameField(
            model_name='vehicleratecategory',
            old_name='tariff_per_km',
            new_name='tariff_per_min',
        ),
        migrations.RemoveField(
            model_name='rate',
            name='oneway_price',
        ),
        migrations.RemoveField(
            model_name='rate',
            name='roundtrip_price',
        ),
        migrations.AlterField(
            model_name='booking',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('POA', 'Pay on arrival'), ('ONL', 'Online'), ('', '')], default='', max_length=3, null=True),
        ),
    ]
